spring.application.name=truesql-pet-clinic
server.port=9966
server.servlet.context-path=/petclinic/api
datasource.url=jdbc:postgresql://localhost:5433/postgres
datasource.username=postgres
datasource.password=1234